export const queryKeys = {
  customers: ["customers"] as const,
  customer: (id: string) => ["customers", id] as const,
  parts: ["parts"] as const,
  part: (id: string) => ["parts", id] as const,
  processMasters: ["processMasters"] as const,
  specifications: ["specifications"] as const,
  standards: ["standards"] as const,
  quotes: ["quotes"] as const,
  quote: (id: string) => ["quotes", id] as const,
  workOrders: ["workOrders"] as const,
  workOrder: (id: string) => ["workOrders", id] as const,
  invoices: ["invoices"] as const,
  certifications: ["certifications"] as const,
  certification: (id: string) => ["certifications", id] as const,
  operators: ["operators"] as const,
  processMaster: (id: string) => ["processMasters", id] as const,
  contactsByCustomer: (customerId: string) => ["contacts", "byCustomer", customerId] as const,
  partsByCustomer: (customerId: string) => ["parts", "byCustomer", customerId] as const,
  priceKeys: ["priceKeys"] as const,
  pricingRulesByPriceKey: (priceKeyId: string) => ["pricingRules", "byPriceKey", priceKeyId] as const,
  scheduleBlocks: ["scheduleBlocks"] as const,
};
